sudo: required

services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_67f650add578_key -iv $encrypted_67f650add578_iv -in multi-k8s-279517-21d0d5c93ea8.json.enc -out multi-k8s-279517-21d0d5c93ea8.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
